// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-vQvNu5eytCO20InLTjB_No3hndbPaYg',
    appId: '1:959557761104:web:bcc82dd4e11810198f3955',
    messagingSenderId: '959557761104',
    projectId: 'fooddoner-8b2bd',
    authDomain: 'fooddoner-8b2bd.firebaseapp.com',
    storageBucket: 'fooddoner-8b2bd.appspot.com',
    measurementId: 'G-7MJLET9ND2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCkCKLD22ht6WeFy2byPlGxNIZ7n4NUtg',
    appId: '1:959557761104:android:72355214cf50a4688f3955',
    messagingSenderId: '959557761104',
    projectId: 'fooddoner-8b2bd',
    storageBucket: 'fooddoner-8b2bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdg98VBqxQwGkIYaztDXUxZ5JZsIgU-Jk',
    appId: '1:959557761104:ios:f21307c7ae82cf6c8f3955',
    messagingSenderId: '959557761104',
    projectId: 'fooddoner-8b2bd',
    storageBucket: 'fooddoner-8b2bd.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdg98VBqxQwGkIYaztDXUxZ5JZsIgU-Jk',
    appId: '1:959557761104:ios:563a53800264b9f88f3955',
    messagingSenderId: '959557761104',
    projectId: 'fooddoner-8b2bd',
    storageBucket: 'fooddoner-8b2bd.appspot.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
